export enum App_ActionType{
// ALLPRODUCTS TYPE *************
// GET PRODUCTS
GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS",
// GET_PRODUCT_FAILURE="GET_PRODUCT_FAILURE",
// GET_PRODUCT_LOADING="GET_PRODUCT_LOADING",


// SINGLE PRODUCT TYPE*************
GET_SINGLE_PRODUCT_SUCCESS="GET_SINGLE_PRODUCT_SUCCESS",


// UPDATE
UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS",
// UPDATE_PRODUCT_FAILURE="UPDATE_PRODUCT_FAILURE",
// UPDATE_PRODUCT_LOADING="UPDATE_PRODUCT_LOADING",

// DELETE
DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS",
// DELETE_PRODUCT_FAILURE="DELETE_PRODUCT_FAILURE",
// DELETE_PRODUCT_LOADING="DELETE_PRODUCT_LOADING",

// POST
POST_PRODUCT_SUCCESS="POST_PRODUCT_SUCCESS",
// POST_PRODUCT_FAILURE="POST_PRODUCT_FAILURE",
// POST_PRODUCT_LOADING="POST_PRODUCT_LOADING",


// ADD_TO_CART *****************
// GET
GET_CART_SUCCESS="GET_CART_SUCCESS",
// GET_CART_FAILURE="GET_CART_FAILURE",
// GET_CART_LOADING="GET_CART_LOADING",

// DELETE
DELETE_CART_SUCCESS="DELETE_CART_SUCCESS",
// DELETE_CART_FAILURE="DELETE_CART_FAILURE",
// DELETE_CART_LOADING="DELETE_CART_LOADING",

// POST
POST_CART_SUCCESS="POST_CART_SUCCESS",
// POST_CART_FAILURE="POST_CART_FAILURE",
// POST_CART_LOADING="POST_CART_LOADING",

// EDIT
UPDATE_CART_SUCCESS="UPDATE_CART_SUCCESS",
// UPDATE_CART_FAILURE="UPDATE_CART_FAILURE",
// UPDATE_CART_LOADING="UPDATE_CART_LOADING",


// WISHLIST **********************
// GET
GET_WISHLIST_SUCCESS="GET_WISHLIST_SUCCESS",
// GET_WISHLIST_FAILURE="GET_WISHLIST_FAILURE",
// GET_WISHLIST_LOADING="GET_WISHLIST_LOADING",

// DELETE
DELETE_WISHLIST_SUCCESS="DELETE_WISHLIST_SUCCESS",
// DELETE_WISHLIST_FAILURE="DELETE_WISHLIST_FAILURE",
// DELETE_WISHLIST_LOADING="DELETE_WISHLIST_LOADING",

// POST
POST_WISHLIST_SUCCESS="POST_WISHLIST_SUCCESS",
// POST_WISHLIST_FAILURE="POST_WISHLIST_FAILURE",
// POST_WISHLIST_LOADING="POST_WISHLIST_LOADING",

// EDIT
UPDATE_WISHLIST_SUCCESS="UPDATE_WISHLIST_SUCCESS",
// UPDATE_WISHLIST_FAILURE="UPDATE_WISHLIST_FAILURE",
// UPDATE_WISHLIST_LOADING="UPDATE_WISHLIST_LOADING",

// ADDRESS **********************
// GET
GET_ADDRESS_SUCCESS="GET_ADDRESS_SUCCESS",
// GET_ADDRESS_FAILURE="GET_ADDRESS_FAILURE",
// GET_ADDRESS_LOADING="GET_ADDRESS_LOADING",

// DELETE
DELETE_ADDRESS_SUCCESS="DELETE_ADDRESS_SUCCESS",
// DELETE_ADDRESS_FAILURE="DELETE_ADDRESS_FAILURE",
// DELETE_ADDRESS_LOADING="DELETE_ADDRESS_LOADING",

// POST
POST_ADDRESS_SUCCESS="POST_ADDRESS_SUCCESS",
// POST_ADDRESS_FAILURE="POST_ADDRESS_FAILURE",
// POST_ADDRESS_LOADING="POST_ADDRESS_LOADING",

// EDIT
UPDATE_ADDRESS_SUCCESS="UPDATE_ADDRESS_SUCCESS",
// UPDATE_ADDRESS_FAILURE="UPDATE_ADDRESS_FAILURE",
// UPDATE_ADDRESS_LOADING="UPDATE_ADDRESS_LOADING",

// LOADING
LOADING="LOADING",

// FAILURE
FAILURE="FAILURE",

}