export enum Auth_Action_Type{
    
    // USER TYPES **************
    // LOGIN
    USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS",
    // USER_LOGIN_LOADING="USER_LOGIN_LOADING",
    // USER_LOGIN_FAILURE="USER_LOGIN_FAILURE",

    // SIGNUP
    USER_SIGNUP_SUCCESS="USER_SIGNUP_SUCCESS",
    // USER_SIGNUP_FAILURE="USER_SIGNUP_FAILURE",
    // USER_SIGNUP_LOADING="USER_SIGNUP_LOADING",

    // DELETE 
    USER_DELETE_SUCCESS="USER_DELETE_SUCCESS",
    // USER_DELETE_FAILURE="USER_DELETE_FAILURE",
    // USER_DELETE_LOADING="USER_DELETE_LOADING",
    

    // ADMIN TYPES ***************
    // GET_CUSTOMER
    GET_USER_SUCCESS="GET_USER_SUCCESS",
    // GET_USER_FAILURE="GET_USER_FAILURE",
    // GET_USER_LOADING="GET_USER_LOADING",

    // GET_MERCHANT 
    GET_MERCHANT_SUCCESS="GET_MERCHANT_SUCCESS",
    // GET_MERCHANT_FAILURE="GET_MERCHANT_FAILURE",
    // GET_MERCHANT_LOADING="GET_MERCHANT_LOADING",

    // LOGIN
    ADMIN_LOGIN_SUCCESS="ADMIN_LOGIN_SUCCESS",
    // ADMIN_LOGIN_FAILURE="ADMIN_LOGIN_FAILURE",
    // ADMIN_LOGIN_LOADING="ADMIN_LOGIN_LOADING",

    // MERCHANT TYPES ***********
    // DELETE
    MERCHANT_DELETE_SUCCESS="MERCHANT_DELETE_SUCCESS",
    // MERCHANT_DELETE_FAILURE="MERCHANT_DELETE_FAILURE",
    // MERCHANT_DELETE_LOADING="MERCHANT_DELETE_LOADING",

    // LOGIN
    MERCHANT_LOGIN_SUCCESS="MERCHANT_LOGIN_SUCCESS",
    // MERCHANT_LOGIN_FAILURE="MERCHANT_LOGIN_FAILURE",
    // MERCHANT_LOGIN_LOADING="MERCHANT_LOGIN_LOADING",

    // SIGNUP
    MERCHANT_SIGNUP_SUCCESS="MERCHANT_SIGNUP_SUCCESS",
    // MERCHANT_SIGNUP_FAILURE="MERCHANT_SIGNUP_FAILURE",
    // MERCHANT_SIGNUP_LOADING="MERCHANT_SIGNUP_LOADING",


    // LODING DATA
    LOADING="LOADING",

    // FAILURE DATA
    FAILURE="FAILURE"

    }